// POV V3.5 (include file)
// Produced by Art of Illusion (Peter Eastman) 2.6.1
//   and POVExporter plugin (Norbert Krieg) version 1.11
//   creation date: Thu Dec 18 13:00:13 CET 2008

// texture declarations
#declare AOIUntitled_1 = 
	texture {
		pigment {
			color <0.9,0.58,0.02>
		}
		finish {
			ambient 0.0
			specular 0.0
			roughness 0.2
		}
	}
#declare AOIUntitled_2 = 
	texture {
		pigment {
			color <0.15,0.12,0.21>
		}
		finish {
			ambient 0.0
			specular 0.0
			roughness 1.0
		}
	}
#declare AOIUntitled_2 = 
	texture {
		pigment {
			color <0.15,0.12,0.21>
		}
		finish {
			ambient 0.0
			specular 0.0
			roughness 1.0
		}
	}
#declare AOIUntitled_2 = 
	texture {
		pigment {
			color <0.15,0.12,0.21>
		}
		finish {
			ambient 0.0
			specular 0.0
			roughness 1.0
		}
	}
#declare AOIUntitled_2 = 
	texture {
		pigment {
			color <0.15,0.12,0.21>
		}
		finish {
			ambient 0.0
			specular 0.0
			roughness 1.0
		}
	}
#declare AOIUntitled_2 = 
	texture {
		pigment {
			color <0.15,0.12,0.21>
		}
		finish {
			ambient 0.0
			specular 0.0
			roughness 1.0
		}
	}
#declare AOIUntitled_2 = 
	texture {
		pigment {
			color <0.15,0.12,0.21>
		}
		finish {
			ambient 0.0
			specular 0.0
			roughness 1.0
		}
	}
