// POV V3.5 (include file)
// Produced by Art of Illusion (Peter Eastman) 2.6.1
//   and POVExporter plugin (Norbert Krieg) version 1.11
//   creation date: Fri Dec 19 12:20:38 CET 2008

// texture declarations
#declare AOIUntitled_1 = 
	texture {
		pigment {
			color <0.1,0.1,0.2>
		}
		finish {
			ambient 0.0
			specular 0
			roughness 0
		}
	}
#declare AOIDefault_Texture = 
	texture {
		pigment {
			color <0.1,0.1,0.2>
		}
		finish {
			ambient 0.0
			specular 0.0
			roughness 0.2
		}
	}
#declare AOIDefault_Texture = 
	texture {
		pigment {
			color <0.1,0.1,0.2>
		}
		finish {
			ambient 0.0
			specular 0.0
			roughness 0.2
		}
	}
